### ISSUE TITLE
Get the data as slice from the captured image

### ISSUE THREAD

**Issue by daniel-abramov** [bryal/dxgcap-rs#3]
At the moment `capture_frame()` returns `Vec<BGRA>`, however most applications which do the further processing of the capture frame (i.e. encode it etc) require `&[u8]` or something similar, in other words, it would be nice to have a direct access to the pixel buffer data.

One of the possible solutions is to use `image::ImageBuffer` type from Piston Developers' `image` crate.

**Comment by bryal** [comment]
This sounds like a great idea! Unfortunately, I  don't really do Windows development anymore. In fact, I don't even have access to a Windows environment to develop this change in :( .

If you, or anybody else, would like to write a pull request yourself, however, I would gladly help you out as much as I can.

**Comment by bryal** [comment]
Closed by #7
